In [1]:
import pandas as pd

df = pd.read_csv("../data/trial_conversion.csv")
df.head()

,user_id,signup_date,signup_source,onboarding_completed,observed_through_date,days_to_conversion_or_censoring,converted
0,1,2024-04-24,referral,False,2024-06-01,4.9,1
1,2,2024-05-23,organic,False,2024-06-01,9.0,0
2,3,2024-04-15,referral,True,2024-06-01,7.5,1
3,4,2024-05-19,paid,False,2024-06-01,13.0,0
4,5,2024-05-27,organic,True,2024-06-01,5.0,0

In [2]:
df["signup_date"] = pd.to_datetime(df["signup_date"])
df["observed_through_date"] = pd.to_datetime(df["observed_through_date"])

df["days_since_signup"] = (df["observed_through_date"] - df["signup_date"]).dt.days
df.head()

,user_id,signup_date,signup_source,onboarding_completed,observed_through_date,days_to_conversion_or_censoring,converted,days_since_signup
0,1,2024-04-24,referral,False,2024-06-01,4.9,1,38
1,2,2024-05-23,organic,False,2024-06-01,9.0,0,9
2,3,2024-04-15,referral,True,2024-06-01,7.5,1,47
3,4,2024-05-19,paid,False,2024-06-01,13.0,0,13
4,5,2024-05-27,organic,True,2024-06-01,5.0,0,5